### ISSUE TITLE
JOSS review: Remove hard-coding of color schemes and line schemes

### ISSUE THREAD

**Issue by kanishkan91** [isakro/shoredate#5]
In some places there is hard coding of color schemes and line schemes- See line 69-78 here- https://github.com/isakro/shoredate/blob/master/R/displacement_plot.R

I think this reduces general usability of this software. For example, if a user wanted to add their own colors, it becomes unneccesarily hard. 

Related to the above, I would recommend that these plot functions just return a plot object that can be plotted with any scheme. 

So, for example this plotting would work like below-

`g <- displacement_plot(sample_data)`

Then, this g can be plotted with any user defined scheme- `g+scheme_basic`

https://github.com/openjournals/joss-reviews/issues/5337

**Comment by isakro** [comment]
Good points! I have now changed it so that most predefined graphical parameters in the plotting functions are instead the defaults of parameters that a user can manipulate.

Furthermore, `target_plot()`, `displacement_plot()` and `shoredate_sumplot()` all return `ggplot` objects that can be manipulated further (also exemplified in the second vignette). E.g.
```
g <- displacement_plot()
g + theme_void()
```

However, one exception to this is `shoredate_plot()`. Due to the many options for how the dating procedure can be performed, the plotting function returns a somewhat convoluted nested list of lists of plots which have to be unpacked in the correct way. I am yet to find a solution that handles this in a way that can return a series of `ggplot` objects instead of sequentially calling `print()` on these. However, if the adjustments that can be done via the plotting arguments of the function is OK for now, I will open this as a separate issue that I can try to deal with at a later stage - I fear it might take quite a bit of effort to resolve.

**Comment by kanishkan91** [comment]
Thanks. Makes sense
